services:
  - docker

env:
  global:
    - RELEASE_VERSION=1.2
    - NOMINATIM_PBF_URL="http://download.geofabrik.de/asia/maldives-latest.osm.pbf"

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - docker build -t nominatim:xenial ./$RELEASE_VERSION
  - docker run -d -p 8080:8080 -e NOMINATIM_PBF_URL=$NOMINATIM_PBF_URL --name nominatim-xenial nominatim:xenial
  - docker build -t nominatim:trusty ./$RELEASE_VERSION/trusty
  - docker run -d -p 8081:8080 -e NOMINATIM_PBF_URL=$NOMINATIM_PBF_URL --name nominatim-trusty nominatim:trusty
  
before_script:
  - npm install newman --global

script:
  - docker ps | grep -q nominatim-xenial
  - ./tests/wait-for-http.sh http://localhost:8080/search
  - newman run tests/nominatim.postman_collection.json -e tests/nominatim-xenial.postman_environment.json
  - docker ps | grep -q nominatim-trusty
  - ./tests/wait-for-http.sh http://localhost:8081/search
  - newman run tests/nominatim.postman_collection.json -e tests/nominatim-trusty.postman_environment.json
